format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](purple)"

[git_branch]
format = "[$branch]($style) "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

